/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-11-10 06:57:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/css/social-buttons.css\" media=\"all\">\n");
      out.write("\n");
      out.write("<div class=\"navbar-inverse navbar-default\" style=\"bottom: 0; inherit; height: 6em; padding-top: 8px;\">\n");
      out.write("\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\n");
      out.write("\t\t<span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\n");
      out.write("\t</button>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"collapse navbar-collapse navbar-ex1-collapse navbar-nav\">\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\" style=\"float: left;\">\n");
      out.write("\t\t\t\t<li><a> Copyright &copy; 2013 - 2014, The T10KT Technical Team, MHRD Project, IIT Bombay. </a>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- /.navbar-collapse  style=\"width: 5\"-->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"collapse navbar-collapse navbar-ex1-collapse pull-right\" >\n");
      out.write("\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"#about\"><i class=\"fa fa-info-circle\"></i> About</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#services\"><i class=\"fa fa-wrench\"></i> Services</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"contactus.htm\"><i class=\"fa fa-mobile\"></i> Contact</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<span class=\"fa-stack fa-lg\"> <a href=\"https://www.facebook.com/recruitment\" class=\"btn btn-social-icon btn-facebook\" target=\"_blank\"><i class=\"fa fa-facebook-square fa-stack-2x\"> </i></a> <a\n");
      out.write("\t\t\t\thref=\"http://www.linkedin.com/recruitment/\" class=\"btn btn-social-icon btn-linkedin\" target=\"_blank\"><i class=\"fa fa-linkedin-square fa-stack-2x\"> </i></a>\n");
      out.write("\t\t\t</span> <span class=\"fa-stack fa-lg\"> <a href=\"https://twitter.com/recruitment\" class=\"btn btn-social-icon btn-twitter\" target=\"_blank\"><i class=\"fa fa-twitter-square fa-stack-2x\"> </i></a> <a\n");
      out.write("\t\t\t\thref=\"https://plus.google.com/recruitment\" class=\"btn btn-social-icon btn-google-plus\" target=\"_blank\"><i class=\"fa fa-google-plus-square fa-stack-2x\"> </i></a>\n");
      out.write("\t\t\t</span>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div id=\"fb-root\"></div>\n");
      out.write("<script>\n");
      out.write("\t(function(d, s, id) {\n");
      out.write("\t\tvar js, fjs = d.getElementsByTagName(s)[0];\n");
      out.write("\t\tif (d.getElementById(id))\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\tjs = d.createElement(s);\n");
      out.write("\t\tjs.id = id;\n");
      out.write("\t\tjs.src = \"//connect.facebook.net/en_US/all.js#xfbml=1\";\n");
      out.write("\t\tfjs.parentNode.insertBefore(js, fjs);\n");
      out.write("\t}(document, 'script', 'facebook-jssdk'));\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/socialButtonScripts.js\"></script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
