/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-11-10 06:57:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.includes;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"./jsp/images/HRMSlogo.png\" />\n");
      out.write("<!-- Add custom CSS here -->\n");
      out.write("<link href=\"./jsp/css/logo-nav.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<nav class=\"navbar-inverse navbar-fixed-top\" role=\"navigation\" style=\"position: absolute;\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t<div class=\"navbar-header\" style=\"padding-left: 5%\">\n");
      out.write("\n");
      out.write("\t\t<!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->\n");
      out.write("\t\t<a class=\"navbar-nav\" href=\"http://mhrd.gov.in\" target=\"_blank\"><img src=\"./jsp/images/MHRDsvg_logo_01.svg\" height=80px></a>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<a class=\"navbar-brand navbar-right\" href=\"http://www.iitb.ac.in\" target=\"_blank\" style=\"padding-right: 5%;\"><img src=\"./jsp/images/iitb-logo.gif\"></a>\n");
      out.write("\t<ul class=\"nav navbar-nav navbar-left\" style=\"margin-top: 0;\">\n");
      out.write("\t\t<li>\n");
      out.write("\t\t\t");
if(session.getAttribute("advtName") != null) { 
      out.write("\n");
      out.write("\t\t\t\t<a><h3>");
      out.print(session.getAttribute("advtName"));
      out.write(" Recruitment</h3></a>\n");
      out.write("\t\t\t");
}
      out.write("\n");
      out.write("\t\t</li>\n");
      out.write("\t</ul>\n");
      out.write("\t</div>\n");
      out.write("</nav>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
