/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-11-10 06:57:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.examhome;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminHome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fid_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fid_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fid_005faction.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>Admin Home ");
      out.print(session.getAttribute("roleName"));
      out.write("</title>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction logout() {\n");
      out.write("\t\tdocument.createexamForm.action = \"examlogout.htm\";\n");
      out.write("\t\tdocument.createexamForm.submit();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction createExam(designationId) {\n");
      out.write("\t\tdocument.homeForm.action = \"createexam.htm?post=\" + designationId;\n");
      out.write("\t\tdocument.homeForm.submit();\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction redirect(designationId) {\n");
      out.write("\t\tdocument.createexamForm.action = \"createexam.htm?post=\" + designationId;\n");
      out.write("\t\tdocument.createexamForm.submit();\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction showCandidatesList(designationId) {\n");
      out.write("\t\tdocument.getElementById(\"hiddenpostname\").value = document.getElementById(\"postname\"+designationId).innerHTML;\n");
      out.write("\t\tdocument.homeForm.action = \"showCandidatesList.htm?post=\" + designationId;\n");
      out.write("\t\tdocument.homeForm.submit();\n");
      out.write("\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction uploadImage(designationId) {\n");
      out.write("\t\tdocument.homeForm.action = \"showuploadpage.htm?post=\" + designationId;\n");
      out.write("\t\tdocument.homeForm.submit();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction redirect(designationId) {\n");
      out.write("\t\tdocument.createexamForm.action = \"createexam.htm?post=\" + designationId;\n");
      out.write("\t\tdocument.createexamForm.submit();\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("      <script src=\"./jsp/js/html5shiv.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("<script src=\"./jsp/js/html5shiv.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/ToggleAccordianImage.js\"></script>\n");
      out.write("<script src=\"./jsp/js/jquery-1.10.2.js\"></script>\n");
      out.write("<script src=\"./jsp/js/bootstrap3.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("$(document).ready(function(){\n");
      out.write("\t $('#top').append('<div id=\"toTop\"><i class=\"fa fa-angle-double-up fa-3x\"></i></div><br/><div id=\"toTop\" style=\"bottom: 90px\">Top</div>');\n");
      out.write("\t\t$(window).scroll(function () {\n");
      out.write("\t\t\tif ($(this).scrollTop() != 0) {\n");
      out.write("\t\t\t\t$('#toTop').fadeIn();\n");
      out.write("\t\t\t} else {\n");
      out.write("\t\t\t\t$('#toTop').fadeOut();\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t$('#toTop').click(function(){\n");
      out.write("\t\t$(\"html, body\").animate({ scrollTop: 0 }, 600);\n");
      out.write("\t\treturn false;\n");
      out.write("\t\t});\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".fa-compress {\n");
      out.write("\tcolor: #3a87ad;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#toTop {\n");
      out.write(" \tborder: 2px solid #f7f7f7; \n");
      out.write("/* \tbackground: black; */\n");
      out.write("\ttext-align: center;\n");
      out.write("\tposition: fixed;\n");
      out.write("\tbottom: 100px;\n");
      out.write("\tright: 50px;\n");
      out.write("\tcursor: pointer;\n");
      out.write("\tdisplay: none;\n");
      out.write("\tcolor: #333;\n");
      out.write("\tfont-family: verdana;\n");
      out.write("\tfont-size: 14px;\n");
      out.write("\topacity: 0.5;\n");
      out.write("\tfilter: alpha(opacity = 40);\n");
      out.write("/* \tpadding: 5px; */\n");
      out.write("}\n");
      out.write("\n");
      out.write("#toTop:hover {\n");
      out.write("\tbackground: #f7f7f7;\n");
      out.write("\topacity: 1;\n");
      out.write(" \tborder: 2px solid #b3b3b3; \n");
      out.write("}\n");
      out.write("​\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../includes/admin-menu.jsp", out, false);
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fid_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /jsp/examhome/adminHome.jsp(103,1) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setId("homeFormId");
      // /jsp/examhome/adminHome.jsp(103,1) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("homeForm");
      // /jsp/examhome/adminHome.jsp(103,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("POST");
      // /jsp/examhome/adminHome.jsp(103,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("#");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t<p style=\"padding-left: 2%;\">\n");
            out.write("\t\t\tWelcome\n");
            out.write("\t\t\t");
            out.print(session.getAttribute("userName"));
            out.write("</p>\n");
            out.write("\t\t<input type=\"hidden\" id=\"hiddenpostname\" name=\"hiddenpostname\">\n");
            out.write("\t\t<div class=\"row\">\n");
            out.write("\t\t\t<div class=\"col-lg-12 panel-info\">\n");
            out.write("\t\t\t\t<div class=\"panel-heading \">\n");
            out.write("\t\t\t\t\t<h3 class=\"panel-title\">\n");
            out.write("\t\t\t\t\t\t<i class=\"fa fa-list-alt\"></i> Click on posts for Creating Exam\n");
            out.write("\t\t\t\t\t</h3>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t\t<div class=\"panel panel-default\">\n");
            out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
            out.write("\t\t\t\t\t\t<div class=\"panel-group\" id=\"accordion\">\n");
            out.write("\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforEach_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t</div>\n");
            out.write("\t\t</div>\n");
            out.write("\t\t<div id=\"top\"></div>\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
        _005fjspx_005ftagPool_005fform_005fform_0026_005fname_005fmethod_005fid_005faction.reuse(_jspx_th_form_005fform_005f0);
      }
      out.write("\n");
      out.write("\t</div>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../includes/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/examhome/adminHome.jsp(118,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("post");
    // /jsp/examhome/adminHome.jsp(118,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/examhome/adminHome.jsp(118,7) '${posts}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${posts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
          out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<h4 class=\"panel-title\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" onclick=\"changeAccordionImage('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\"> <span\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\tid=\"postname");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" name=\"postname");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</span> <i id=\"accordionImage");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"fa fa-expand pull-right\"></i></a>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</h4>\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t<div id=\"collapse");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"panel-collapse collapse\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\" style=\"background-color: #fffefa\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationDescription}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</p>\n");
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn\" onclick=\"showCandidatesList(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(")\">Open Candidates List</button>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<button class=\"btn btn-primary btn\" onclick=\"uploadImage(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(")\">Upload Images of Candidates</button>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\"></div>\n");
          out.write("\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
