/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-11-11 06:11:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.questionbank;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addquestion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/jsp/questionbank/../includes/admin-menu.jsp", Long.valueOf(1410310552000L));
    _jspx_dependants.put("/jsp/questionbank/../includes/footer.jsp", Long.valueOf(1410310552000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

HttpSession httpSession = request.getSession(false);
if(httpSession.getAttribute("email") == null || httpSession.getAttribute("email").toString() == null) { 
      out.write('\n');
      out.write('	');
      out.write('	');
      if (true) {
        _jspx_page_context.forward("/sessionexpired.htm");
        return;
      }
      out.write('\n');
	} else { 
      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<meta name=\"description\" content=\"\">\n");
      out.write("<meta name=\"author\" content=\"\">\n");
      out.write("<link rel=\"icon\" type=\"image/png\" href=\"./jsp/images/iitb.jpg\" />\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html;charset=utf-8\" />\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction redirect(path) {\n");
      out.write("\t\tdocument.menuForm.action = path;\n");
      out.write("\t\t//document.menuForm.method=\"POST\";\n");
      out.write("\t\tdocument.menuForm.submit();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction showDefaultImage(img) {\n");
      out.write("\t\timg.src=\"user_images/default.png\";\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("      <script src=\"./jsp/js/html5shiv.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("<script src=\"./jsp/js/html5shiv.js\"></script>\n");
      out.write("<script src=\"./jsp/js/respond.js\" type=\"text/javascipt\"> </script>\n");
      out.write("\n");
      out.write("<!-- Bootstrap core CSS -->\n");
      out.write("<link href=\"./jsp/css/bootstrap3.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- Add custom CSS here -->\n");
      out.write("<link href=\"./jsp/css/font-awesome.css\" rel=\"stylesheet\" />\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("\tmargin-top: 5%;\n");
      out.write("\twidth: 100%;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".dropdown-menu li>a:hover {\n");
      out.write("\tcolor: #ffffff;\n");
      out.write("\ttext-decoration: none;\n");
      out.write("\tbackground-color: #0077b3;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li ul .dropdown-menu {\n");
      out.write("\t-webkit-transition: width 15s; /* For Safari 3.1 to 6.0 */\n");
      out.write("\ttransition: width 15s;\n");
      out.write("\tbackground-color: #0077b3;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\t<form method=\"post\" name=\"menuForm\">\n");
      out.write("\t\t<div class=\"navbar-inverse navbar-fixed-top navbar-inner\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t\t<button type=\"button\" data-target=\"#navbarCollapse\" data-toggle=\"collapse\" class=\"navbar-toggle\">\n");
      out.write("\t\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"brand navbar-right\"> <img src=\"./jsp/images/iitb-logo.gif\" style=\"\" width=180px height=50px />\n");
      out.write("\t\t\t\t</a> <a class=\"brand\" href=\"http://mhrd.gov.in\" target=\"_blank\" style=\"float: left;\"> <img src=\"./jsp/images/MHRDsvg_logo_01.svg\" height=50px />\n");
      out.write("\t\t\t\t</a>\n");
      out.write("\t\t\t\t<div id=\"navbarCollapse\" class=\"collapse navbar-collapse\">\n");
      out.write("\t\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" onclick=\"redirect('examhome.htm')\"><i class=\"fa fa-home fa-1x\"></i> Home</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a data-toggle=\"dropdown\" href=\"#\"><i class=\"fa fa-tags fa-1x\"></i> Advertisements <span class=\"caret\"></span></a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"#\">Advt. 1</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"#\">Advt. 2</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a data-toggle=\"dropdown\" href=\"#\"><i class=\"fa fa-gears fa-1x\"></i> Admin <span class=\"caret\"></span></a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"redirect('createexammanual.htm')\"> <span>Create Exam</span>\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"redirect('addquestion.htm')\"> <span>Add Questions</span>\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"redirect('displayallquestions.htm')\"> <span>View Questions</span>\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a data-toggle=\"dropdown\" href=\"#\" onclick=\"#\"><i class=\"fa fa-unlock fa-1x\"></i> Current Openings</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li><a onclick=\"#\"> <span><i class=\"fa fa-question fa-1x\" style=\"font-size: 16px;\"></i> Help</span>\n");
      out.write("\t\t\t\t\t\t</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t<li class=\"dropdown\"><a class=\"dropdown-toggle\" data-toggle=\"dropdown\" href=\"#\"> <img src=\"user_images/");
      out.print(session.getAttribute("userid"));
      out.write(".jpg\" onerror=\"showDefaultImage(this)\"\n");
      out.write("\t\t\t\t\t\t\t\twidth=20px /> ");
      out.print(session.getAttribute("userName"));
      out.write(" <span class=\"caret\"></span>\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"dropdown-menu\" style=\"width: auto;\">\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\"><i class=\"fa fa-envelope\"></i> ");
      out.print(session.getAttribute("email"));
      out.write("</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"#\"> <i class=\"fa fa-eye\"></i> View Profile\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"#\"> <i class=\"fa fa-edit fa-1g\"></i> Edit Profile\n");
      out.write("\t\t\t\t\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t\t\t\t\t<li><a href=\"#\" onclick=\"redirect('examlogout.htm');\"><i class=\"fa fa-sign-out fa-1x\"></i> Sign out </a></li>\n");
      out.write("\t\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("\t<!-- JavaScript -->");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0 maximum-scale=1\">\n");
      out.write("<title>");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/jquery-1.10.2.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/bootstrap.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/html5shiv.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/respond.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/jquery.validate.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"../js/script.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/bootstrap.css\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/style.css\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("\tpadding-left: 5%;\n");
      out.write("\tpadding-right: 5%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function addQuestionDiv() {\n");
      out.write("\ttry {\n");
      out.write("\t\tvar questionType = (document.getElementById(\"qtypeid\").options[document\n");
      out.write("\t\t\t\t.getElementById(\"qtypeid\").selectedIndex].value);\n");
      out.write("\t\t//alert(\"qtype: \" + qtype);\n");
      out.write("\n");
      out.write("\t\tswitch (questionType) {\n");
      out.write("\t\tcase '1':\n");
      out.write("\t\t\t$('#addQuestion').load(\"addsinglechoicequestion.htm\");\n");
      out.write("\t\t\t//alert(\"single choice\");\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\tcase '2':\n");
      out.write("\t\t\t$('#addQuestion').load(\"addmultiplechoicequestion.htm\");\t\t\t\t\t\t\n");
      out.write("\t\t\t//alert(\"Multiple choice\");\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\tcase '3':\n");
      out.write("\t\t\t$('#addQuestion').load(\"addcomprehensionquestion.htm\");\n");
      out.write("\t\t\t//alert(\"comprehension\")\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\tcase '4':\n");
      out.write("\t\t\t$('#addQuestion').load(\"addsequencequestion.htm\");\n");
      out.write("\t\t\t//alert(\"sequence\");\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\tcase '5':\n");
      out.write("\t\t\t$('#addQuestion').load(\"addcodingquestion.htm\");\n");
      out.write("\t\t\t//alert(\"sourcecode\");\n");
      out.write("\t\t\tbreak;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t} catch (err) {\n");
      out.write("\t\talert(\"Error: \" + err.message);\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("$(document).ready(function(){\n");
      out.write("    $('select#qpoolforadvtid').on('change', function() {\n");
      out.write("         var value = this.value;\n");
      out.write("        var advtName = document.getElementById(\"qpoolforadvtid\").options[document.getElementById(\"qpoolforadvtid\").selectedIndex].text;\n");
      out.write("          if(value ==\"select\") {\n");
      out.write("              $('#designation').html(\"\");\n");
      out.write("              return false;\n");
      out.write("          }\n");
      out.write("          else if(advtName==\"General\") {\n");
      out.write("        \t  $('#designation').html(\"\");\n");
      out.write("              return false;\n");
      out.write("          }\n");
      out.write("          else {\n");
      out.write("              $('#designation').load(\"designationcontrol.htm?Value=\"+value);\n");
      out.write("                document.getElementById(\"designation\").style.visibility=\"visible\";\n");
      out.write("           \n");
      out.write("          }\n");
      out.write("         \n");
      out.write("    });\n");
      out.write("\n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<form name=\"addquestionform\" class=\"form-horizontal\" action=\"addedsuccessfully.htm\" method=\"post\">\n");
      out.write("\t<div class=\"row col-lg-12\">\n");
      out.write("\t<div class=\"panel panel-info\">\n");
      out.write("\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t<h3 class=\"panel-title\">Online Examination - Add Questions to Question Bank</h3>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t<label for=\"addQuestionTag\" class=\"col-sm-4 control-label\">");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("<br><span><sub>(For ex. Java, Python, C etc...)</sub></span></label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"addQuestionCategory\"\n");
      out.write("\t\t\t\t\t\t\tid=\"addQuestionCategoryId\" list=\"categoryList\" placeholder=\"Please enter the Question Category\" required />\n");
      out.write("\t\t\t\t\t\t<datalist id=\"categoryList\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"General Knowledge (GK)/ Current Affairs\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Mathematical / Quantitative Aptitude\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Verbal / Logical Reasoning\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"C - Programming\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"C++ - Programming\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Java - Programming\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Python - Programming\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Scilab - Programming\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"PHP/MySQL - Programming\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Database Management Systems (DBMS)\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Others\">\n");
      out.write("\t\t\t\t\t\t</datalist>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t<label for=\"emailId\" class=\"col-sm-4 control-label\">");
      if (_jspx_meth_spring_005fmessage_005f2(_jspx_page_context))
        return;
      out.write("<br><span><sub>(Select Advt. and designation for the question)</sub></span></label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" name=\"qpoolforadvt\" id=\"qpoolforadvtid\"  data-toggle=\"designation\" required>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"select\">-- Select --</option>\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t\t\t\t</select>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"form-group\" id=\"designation\" style=\"visibility: hidden\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t<label for=\"lod\" class=\"col-sm-4 control-label\">");
      if (_jspx_meth_spring_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("<br><span><sub>(Select the level of difficulty based on 1-5)</sub></span></label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" name=\"lod\" id=\"lodid\" required>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"select\">-- Select --</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"1\">1</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">2</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">3</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">4</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">5</option>\n");
      out.write("\t\t\t\t\t\t</select>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<div id=\"questiontype\" class=\"form-group\">\n");
      out.write("\t\t\t\t<label for=\"qtype\" class=\"col-sm-4 control-label\">");
      if (_jspx_meth_spring_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("<br><span><sub>(Select Single choice, multiple choice etc...)</sub></span></label>\n");
      out.write("\t\t\t\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t\t\t\t<select class=\"form-control\" name=\"qtype\" id=\"qtypeid\" onchange=\"addQuestionDiv();\" required>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"select\">-- Select --</option>\n");
      out.write("\t\t\t\t\t\t    <option value=\"1\">Single Choice Questions</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"2\">Multiple Choice Questions</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"3\">Comprehension Questions</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"4\">Sequencing Questions</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"5\">Source Code Questions</option>\n");
      out.write("\t\t\t\t\t\t</select>\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<div class=\"page-header\"></div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<div id=\"addQuestion\" class=\"form-group\">\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"page-header\"></div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t<div class=\"col-sm-offset-4 col-sm-10\">\n");
      out.write("\t\t\t\t\t<br /><button type=\"submit\" class=\"btn btn-primary\"><i class=\"fa fa-check\"></i> Add to Question Bank</button>\n");
      out.write("\t\t\t\t\t<button type=\"reset\" class=\"btn btn-default\"><i class=\"fa fa-eraser\"></i> Reset</button>\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-danger\" formaction=\"examhome.htm\"><i class=\"fa fa-times\"></i> Cancel</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"panel-footer\"></div>\n");
      out.write("\t</div>\t\t\t\t\t\n");
      out.write("</div>\n");
      out.write("</form>\t\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/css/social-buttons.css\" media=\"all\">\n");
      out.write("\n");
      out.write("<div class=\"navbar-inverse navbar-default\" style=\"bottom: 0; inherit; height: 6em; padding-top: 8px;\">\n");
      out.write("\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-ex1-collapse\">\n");
      out.write("\t\t<span class=\"sr-only\">Toggle navigation</span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span>\n");
      out.write("\t</button>\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"collapse navbar-collapse navbar-ex1-collapse navbar-nav\">\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\" style=\"float: left;\">\n");
      out.write("\t\t\t\t<li><a> Copyright &copy; 2013 - 2014, The T10KT Technical Team, MHRD Project, IIT Bombay. </a>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<!-- /.navbar-collapse  style=\"width: 5\"-->\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"collapse navbar-collapse navbar-ex1-collapse pull-right\" >\n");
      out.write("\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t<li><a href=\"#about\"><i class=\"fa fa-info-circle\"></i> About</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"#services\"><i class=\"fa fa-wrench\"></i> Services</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"contactus.htm\"><i class=\"fa fa-mobile\"></i> Contact</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<span class=\"fa-stack fa-lg\"> <a href=\"https://www.facebook.com/recruitment\" class=\"btn btn-social-icon btn-facebook\" target=\"_blank\"><i class=\"fa fa-facebook-square fa-stack-2x\"> </i></a> <a\n");
      out.write("\t\t\t\thref=\"http://www.linkedin.com/recruitment/\" class=\"btn btn-social-icon btn-linkedin\" target=\"_blank\"><i class=\"fa fa-linkedin-square fa-stack-2x\"> </i></a>\n");
      out.write("\t\t\t</span> <span class=\"fa-stack fa-lg\"> <a href=\"https://twitter.com/recruitment\" class=\"btn btn-social-icon btn-twitter\" target=\"_blank\"><i class=\"fa fa-twitter-square fa-stack-2x\"> </i></a> <a\n");
      out.write("\t\t\t\thref=\"https://plus.google.com/recruitment\" class=\"btn btn-social-icon btn-google-plus\" target=\"_blank\"><i class=\"fa fa-google-plus-square fa-stack-2x\"> </i></a>\n");
      out.write("\t\t\t</span>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("<div id=\"fb-root\"></div>\n");
      out.write("<script>\n");
      out.write("\t(function(d, s, id) {\n");
      out.write("\t\tvar js, fjs = d.getElementsByTagName(s)[0];\n");
      out.write("\t\tif (d.getElementById(id))\n");
      out.write("\t\t\treturn;\n");
      out.write("\t\tjs = d.createElement(s);\n");
      out.write("\t\tjs.id = id;\n");
      out.write("\t\tjs.src = \"//connect.facebook.net/en_US/all.js#xfbml=1\";\n");
      out.write("\t\tfjs.parentNode.insertBefore(js, fjs);\n");
      out.write("\t}(document, 'script', 'facebook-jssdk'));\n");
      out.write("</script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/socialButtonScripts.js\"></script>");
      out.write('\n');
}
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent(null);
    // /jsp/questionbank/addquestion.jsp(18,7) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setCode("onlinetest.addquestion.title");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent(null);
    // /jsp/questionbank/addquestion.jsp(103,63) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setCode("onlinetest.addquestion.category");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f2.setParent(null);
    // /jsp/questionbank/addquestion.jsp(125,56) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f2.setCode("onlinetest.addquestion.advt");
    int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
      if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /jsp/questionbank/addquestion.jsp(130,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("advertisement");
    // /jsp/questionbank/addquestion.jsp(130,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/questionbank/addquestion.jsp(130,7) '${advts}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${advts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("  \t\t\t\t\t\t\t\t<option value='");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write('\'');
          out.write('>');
          if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("</option>\n");
          out.write("  \t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /jsp/questionbank/addquestion.jsp(131,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advertisement.advertisementId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /jsp/questionbank/addquestion.jsp(131,76) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${advertisement.advertisementTitle}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f3.setParent(null);
    // /jsp/questionbank/addquestion.jsp(142,52) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f3.setCode("onlinetest.addquestion.lod");
    int[] _jspx_push_body_count_spring_005fmessage_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f3 = _jspx_th_spring_005fmessage_005f3.doStartTag();
      if (_jspx_th_spring_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f3.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f4.setParent(null);
    // /jsp/questionbank/addquestion.jsp(157,54) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f4.setCode("onlinetest.addquestion.qtype");
    int[] _jspx_push_body_count_spring_005fmessage_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f4 = _jspx_th_spring_005fmessage_005f4.doStartTag();
      if (_jspx_th_spring_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f4.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f4);
    }
    return false;
  }
}
