/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-11-11 06:12:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.questionbank;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class addsinglechoicequestion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fckeditor_005freplace_0026_005freplace_005fbasePath_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fckeditor_005freplace_0026_005freplace_005fbasePath_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fckeditor_005freplace_0026_005freplace_005fbasePath_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/bootstrap.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/jquery-1.10.2.js\"></script>\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"../css/bootstrap.css\" />\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("var ctr = 4;\n");
      out.write("function addOption()\n");
      out.write("{\n");
      out.write("\tif(ctr<6)\n");
      out.write("\t\t{\n");
      out.write("\t\ttry\n");
      out.write("\t\t{\n");
      out.write("\t\t\tctr++;\n");
      out.write("\t\t\tvar div = document.createElement(\"div\");\n");
      out.write("\t\t\tvar label = document.createElement(\"span\");\n");
      out.write("\t\t\tvar radioButton = document.createElement(\"input\");\n");
      out.write("\t\t\tvar textbox = document.createElement(\"input\");\n");
      out.write("\t\t\tvar removeButton = document.createElement(\"a\");\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t\tdiv.setAttribute(\"class\", \"radio\")\n");
      out.write("\t\t\tdiv.setAttribute(\"id\", \"div\"+ctr)\n");
      out.write("\t\t\tlabel.setAttribute(\"id\", \"span\"+ctr)\n");
      out.write("\t\t\tradioButton.setAttribute(\"type\", \"radio\");\n");
      out.write("\t\t\tradioButton.setAttribute(\"name\", \"option\");\n");
      out.write("\t\t\tradioButton.setAttribute(\"value\", ctr);\n");
      out.write("\t\t\tradioButton.setAttribute(\"id\", \"radio\"+ctr);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\ttextbox.setAttribute(\"name\", \"\"+ctr);\n");
      out.write("\t\t\ttextbox.setAttribute(\"type\", \"text\");\n");
      out.write("\t\t\ttextbox.setAttribute(\"id\",\"txt\"+ctr);\n");
      out.write("\t\t\ttextbox.setAttribute(\"class\", \"form-control\");\n");
      out.write("\t\t\ttextbox.setAttribute(\"placeholder\", \"Enter option \"+ctr)\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tcatch(err)\n");
      out.write("\t\t{\n");
      out.write("\t\t\talert(err.message);\n");
      out.write("\t\t}\n");
      out.write("\t\ttry\n");
      out.write("\t\t{\n");
      out.write("\t\n");
      out.write("\t\t\tremoveButton.setAttribute(\"href\", \"javascript:removeOption(\"+(ctr)+\")\");\n");
      out.write("\t\t\tremoveButton.setAttribute(\"id\",\"remove\"+(ctr));\n");
      out.write("\t\t\tremoveButton.setAttribute(\"class\",\"glyphicon glyphicon-minus-sign\");\n");
      out.write("\t\t\tremoveButton.setAttribute(\"style\",\"width:20px;\");\n");
      out.write("\t\t}\n");
      out.write("\t\tcatch(err)\n");
      out.write("\t\t{\n");
      out.write("\t\t\talert(err.message);\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\ttry\n");
      out.write("\t\t{\n");
      out.write("\t\t\tvar before=document.getElementById(\"singleadd\");\n");
      out.write("\t\t\tvar par=before.parentNode;\n");
      out.write("\t\t\tdiv.appendChild(label);\n");
      out.write("\t\t\tdiv.appendChild(radioButton);\n");
      out.write("\t\t\tdiv.appendChild(textbox);\n");
      out.write("\t\t\tdiv.appendChild(removeButton);\n");
      out.write("\t\t\tpar.insertBefore(div,before);\n");
      out.write("\t\t\tlabel.innerHTML=(String.fromCharCode(64+ctr));\n");
      out.write("\t\t\tdocument.getElementById(\"count\").value=ctr;\n");
      out.write("\t\t}\n");
      out.write("\t\tcatch(err)\n");
      out.write("\t\t{\n");
      out.write("\t\t\talert(err.message);\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Options not more than 6!\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("function removeOption(opt)\n");
      out.write("{\n");
      out.write("\tvar i=0;\n");
      out.write("\t//alert(ctr);\n");
      out.write("\tif(ctr>4)\n");
      out.write("\t{\n");
      out.write("\t\tfor(i=opt;i<ctr;i++)\n");
      out.write("\t\t{\t\n");
      out.write("\t\t\tdocument.getElementById(\"txt\"+i).value=document.getElementById(\"txt\"+(i+1)).value;\n");
      out.write("\t\t\tdocument.getElementById(\"radio\"+i).checked = document.getElementById(\"radio\"+(i+1)).checked;\n");
      out.write("\t\t}\n");
      out.write("\t\ttry\n");
      out.write("\t\t{\n");
      out.write("\t\t//\talert(\"Assigning!\");\n");
      out.write("\t\t\tvar child1=document.getElementById(\"div\"+ctr);\n");
      out.write("\t\t\tvar parent=document.getElementById(\"parent\");\n");
      out.write("\t\t\tparent.removeChild(child1);\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\tcatch(err)\n");
      out.write("\t\t{\n");
      out.write("\t\t\talert(\"here---\"+err.message);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\tctr--;\n");
      out.write("\t\t\n");
      out.write("\t\tdocument.getElementById(\"count\").value=ctr;\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t{\n");
      out.write("\t\talert(\"Options must be more than 4!\");\n");
      out.write("\t}\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("</script> \n");
      out.write("<!-- <form name=\"singleChoiceQuestionForm\" method=\"post\"> -->\n");
      out.write("\t<div class=\"form-group\" onload=\"getCKEditorContents();\">\n");
      out.write("\t\t<label for=\"qtype\" class=\"col-sm-4 control-label\">");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</label>\n");
      out.write("\t\t<div class=\"col-sm-6\">\n");
      out.write("\t\t\t<textarea  name=\"qText\" id=\"qTextId\" class=\"form-control\" rows=\"4\" cols=\"50\" draggable=\"false\" placeholder=\"Enter your Single Choice question here...\"></textarea>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t");
      if (_jspx_meth_ckeditor_005freplace_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<div class=\"form-group\">\n");
      out.write("\t\t<label for=\"options\" class=\"col-sm-4 control-label\">");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</label><br />\n");
      out.write("\t\t<div id=\"parent\" class=\"col-sm-6\">\n");
      out.write("\t\t\t<div id=\"div1\" class=\"radio\">\n");
      out.write("\t\t\t\t<span id=\"span1\">A</span><input type=\"radio\" name=\"option\" id=\"radio1\" value=\"1\" checked>\n");
      out.write("\t\t\t\t <input class=\"form-control\" type=\"text\" name=\"1\" id=\"txt1\" placeholder=\"Enter option 1\" required />\n");
      out.write("\t\t\t\t <a  style=\"width:20px \"class =\"glyphicon glyphicon-minus-sign\" id = \"remove1\" href=\"javascript:removeOption(1)\"></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"div2\" class=\"radio\">\n");
      out.write("\t\t\t\t<span id=\"span2\">B</span><input type=\"radio\" name=\"option\" id=\"radio2\" value=\"2\">\n");
      out.write("\t\t\t\t <input class=\"form-control\" type=\"text\" name=\"2\" id=\"txt2\" placeholder=\"Enter option 2\" required />\n");
      out.write("\t\t\t\t <a  style=\"width:20px \"class =\"glyphicon glyphicon-minus-sign\" id = \"remove2\" href=\"javascript:removeOption(2)\"></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"div3\" class=\"radio\">\n");
      out.write("\t\t\t\t<span id=\"span3\">C</span><input type=\"radio\" name=\"option\" id=\"radio3\" value=\"3\">\n");
      out.write("\t\t\t\t <input class=\"form-control\" type=\"text\" name=\"3\" id=\"txt3\" placeholder=\"Enter option 3\" required />\n");
      out.write("\t\t\t\t<a  style=\"width:20px \"class =\"glyphicon glyphicon-minus-sign\" id = \"remove3\" href=\"javascript:removeOption(3)\"></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div id=\"div4\" class=\"radio\">\n");
      out.write("\t\t\t\t<span id=\"span4\">D</span><input type=\"radio\" name=\"option\" id=\"radio4\" value=\"4\">\n");
      out.write("\t\t\t\t <input class=\"form-control\" type=\"text\" name=\"4\" id=\"txt4\" placeholder=\"Enter option 4\" required />\n");
      out.write("\t\t\t\t <a style=\"width:20px \"class =\"glyphicon glyphicon-minus-sign\" id = \"remove4\" href=\"javascript:removeOption(4)\"></a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"count\" name=\"count\" value=\"4\"/>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div id= \"singleadd\" class=\"form-group\">\n");
      out.write("\t\t\t\t<button class=\"btn btn-success\" type=\"button\" onclick = \"addOption( );\">\n");
      out.write("\t\t\t\t\t<span class=\"glyphicon glyphicon-plus-sign\"></span> Add Option\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\t\n");
      out.write("\t</div>\n");
      out.write("<!-- </form> -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent(null);
    // /jsp/questionbank/addsinglechoicequestion.jsp(122,52) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setCode("onlinetest.addquestion.qtext");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_ckeditor_005freplace_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  ckeditor:replace
    com.ckeditor.CKEditorReplaceTag _jspx_th_ckeditor_005freplace_005f0 = (com.ckeditor.CKEditorReplaceTag) _005fjspx_005ftagPool_005fckeditor_005freplace_0026_005freplace_005fbasePath_005fnobody.get(com.ckeditor.CKEditorReplaceTag.class);
    _jspx_th_ckeditor_005freplace_005f0.setPageContext(_jspx_page_context);
    _jspx_th_ckeditor_005freplace_005f0.setParent(null);
    // /jsp/questionbank/addsinglechoicequestion.jsp(128,2) name = replace type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ckeditor_005freplace_005f0.setReplace("qText");
    // /jsp/questionbank/addsinglechoicequestion.jsp(128,2) name = basePath type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_ckeditor_005freplace_005f0.setBasePath("./ckeditor/");
    int _jspx_eval_ckeditor_005freplace_005f0 = _jspx_th_ckeditor_005freplace_005f0.doStartTag();
    if (_jspx_th_ckeditor_005freplace_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fckeditor_005freplace_0026_005freplace_005fbasePath_005fnobody.reuse(_jspx_th_ckeditor_005freplace_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fckeditor_005freplace_0026_005freplace_005fbasePath_005fnobody.reuse(_jspx_th_ckeditor_005freplace_005f0);
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent(null);
    // /jsp/questionbank/addsinglechoicequestion.jsp(133,54) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setCode("onlinetest.addquestion.qoption");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }
}
