/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-11-10 06:57:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.exam;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class examlogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fform_005fform_0026_005fng_002dsubmit_005fname_005fmethod_005fdata_002dtoggle_005fclass_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fform_005fform_0026_005fng_002dsubmit_005fname_005fmethod_005fdata_002dtoggle_005fclass_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fform_005fform_0026_005fng_002dsubmit_005fname_005fmethod_005fdata_002dtoggle_005fclass_005faction.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\" data-scribe-reduced-action-queue=\"true\">\n");
      out.write("<!--<![endif]-->\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0 maximum-scale=1\">\n");
      out.write("<!-- <meta charset = \"UTF-8\"> -->\n");
      out.write("<!-- <meta name = \"viewport\" content = \"width=device-width , initail-scale=1.0\"/> -->\n");
      out.write("<!-- <meta name = \"description\" content=\"\" /> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<title>");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_page_context))
        return;
      out.write("</title>\n");
      out.write("<!-- Respond.js redirect location on local server -->\n");
      out.write("<script src=\"./jsp/js/respond.js\" type=\"text/javascipt\"></script>\n");
      out.write("<script src=\"./jsp/js/html5shiv.js\" type=\"text/javascipt\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/ToggleAccordianImage.js\"></script>\n");
      out.write("<script src=\"./jsp/js/jquery-1.10.2.js\"></script>\n");
      out.write("<script src=\"./jsp/js/bootstrap.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/newsticker/jquery.easing.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/newsticker/jquery.easy-ticker.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"./jsp/js/slidepanel/jquery.slidePanel.js\"></script>\n");
      out.write("<!-- <script src=\"./jsp/js/validation/validator.js\"></script> -->\n");
      out.write("\n");
      out.write("<script src=\"./jsp/js/angular.min.js\"></script>\n");
      out.write("<script src=\"./jsp/js/app.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("\t\t$(\".form-control\").tooltip();\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction redirect(path) {\n");
      out.write("\t\tdocument.menuForm.action = path;\n");
      out.write("\t\tdocument.menuForm.submit();\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction forgotPassword() {\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\ttype : \"POST\",\n");
      out.write("\t\t\tcache : false,\n");
      out.write("\t\t\turl : \"forgot.htm\",\n");
      out.write("\t\t\tsuccess : function(response) {\n");
      out.write("\t\t\t\tdocument.getElementById(\"forgotPassword\").innerHTML = response;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction validateForgotPassForm() {\n");
      out.write("\t\tvar result = true;\n");
      out.write("\t\tvar email = document.getElementById('emailId').value;\n");
      out.write("\t\tvar emailRegX = /^[\\w\\-\\.\\+]+\\@[a-zA-Z0-9\\.\\-]+\\.[a-zA-z0-9]{2,4}$/;\n");
      out.write("\t\tif (!email.match(emailRegX)) {\n");
      out.write("\t\t\tresult = false;\n");
      out.write("\t\t\t$('#emailId').addClass('has-error');\n");
      out.write("\t\t\tdocument.getElementById('error').style.display = \"block\";\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\tdocument.getElementById('error').style.display = \"none\";\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\ttype : \"POST\",\n");
      out.write("\t\t\t\tcache : false,\n");
      out.write("\t\t\t\turl : \"forgotPasswordFormAction.htm\",\n");
      out.write("\t\t\t\tdata : \"emailId=\" + email,\n");
      out.write("\t\t\t\tsuccess : function(response) {\n");
      out.write("\t\t\t\t\tif(response.trim() == \"notReg\") {\n");
      out.write("\t\t\t\t\t\t$('#errorReg').show();\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\tif(response.trim() == 'reg') {\n");
      out.write("\t\t\t\t\t\tlocation.replace(\"forgotPasswordLinkSend.htm\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t}\n");
      out.write("\t\treturn result;\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction addErrorMsgForForgotPass() {\n");
      out.write("\t\t$('#error').html('<div class=\"alert alert-danger alert-dismissable col-sm-offset-2 col-sm-6\">'+\n");
      out.write("\t\t\t\t'<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\" onclick=\"addErrorMsgForForgotPass()\">&times;</button>'+\n");
      out.write("\t\t\t\t'<p>Enter valid email.</p></div>');\n");
      out.write("\t\t$('#error').hide();\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document)\n");
      out.write("\t\t\t.ready(\n");
      out.write("\t\t\t\t\tfunction() {\n");
      out.write("\t\t\t\t\t\tvar pageTitle = document.title; //HTML page title\n");
      out.write("\t\t\t\t\t\tvar pageUrl = location.href; //Location of the page\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t//user hovers on the share button\t\n");
      out.write("\t\t\t\t\t\t$('#share-wrapper li').hover(function() {\n");
      out.write("\t\t\t\t\t\t\tvar hoverEl = $(this); //get element\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t//browsers with width > 699 get button slide effect\n");
      out.write("\t\t\t\t\t\t\tif ($(window).width() > 699) {\n");
      out.write("\t\t\t\t\t\t\t\tif (hoverEl.hasClass('visible')) {\n");
      out.write("\t\t\t\t\t\t\t\t\thoverEl.animate({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"margin-left\" : \"-120px\"\n");
      out.write("\t\t\t\t\t\t\t\t\t}, \"fast\").removeClass('visible');\n");
      out.write("\t\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\t\thoverEl.animate({\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"margin-left\" : \"0px\"\n");
      out.write("\t\t\t\t\t\t\t\t\t}, \"fast\").addClass('visible');\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t//user clicks on a share button\n");
      out.write("\t\t\t\t\t\t$('.button-wrap')\n");
      out.write("\t\t\t\t\t\t\t\t.click(\n");
      out.write("\t\t\t\t\t\t\t\t\t\tfunction(event) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tvar shareName = $(this).attr(\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'class').split(' ')[0]; //get the first class name of clicked element\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tswitch (shareName) //switch to different links based on different social name\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t{\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcase 'facebook':\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar openLink = 'https://www.facebook.com/sharer/sharer.php?u='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageUrl)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '&amp;title='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageTitle);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcase 'twitter':\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar openLink = 'http://twitter.com/home?status='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageTitle\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ' ' + pageUrl);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcase 'digg':\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar openLink = 'http://www.digg.com/submit?phase=2&amp;url='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageUrl)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '&amp;title='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageTitle);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcase 'stumbleupon':\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar openLink = 'http://www.stumbleupon.com/submit?url='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageUrl)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '&amp;title='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageTitle);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcase 'delicious':\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar openLink = 'http://del.icio.us/post?url='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageUrl)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '&amp;title='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageTitle);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcase 'google':\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar openLink = 'https://plus.google.com/share?url='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageUrl)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '&amp;title='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ encodeURIComponent(pageTitle);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tcase 'email':\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tvar openLink = 'mailto:?subject='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ pageTitle\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ '&body=Found this useful link for you : '\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ pageUrl;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//Parameters for the Popup window\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twinWidth = 650;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twinHeight = 450;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\twinLeft = ($(window)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.width() - winWidth) / 2,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\twinTop = ($(window)\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t.height() - winHeight) / 2,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\twinOptions = 'width='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ winWidth\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ',height='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ winHeight\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ',top=' + winTop\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ ',left='\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t+ winLeft;\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t//open Popup window and redirect user to share website.\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\twindow.open(openLink,\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t'Share This Link',\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\twinOptions);\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\treturn false;\n");
      out.write("\t\t\t\t\t\t\t\t\t\t});\n");
      out.write("\t\t\t\t\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<link href=\"./jsp/css/font-awesome.css\" rel=\"stylesheet\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/css/bootstrap.css\" media=\"all\">\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"./jsp/css/slider.css\" media=\"all\">\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".fa-compress {\n");
      out.write("\tcolor: #3a87ad;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input.ng-valid {\n");
      out.write("\tborder: 1px solid green;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body ng-app=\"validationApp\" ng-controller=\"mainController\">\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<div class=\"panel-body\">\n");
      out.write("\t\t\t<div id=\"forgotPassword\" class=\"modal fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\"></div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../includes/header.jsp", out, false);
      out.write("\n");
      out.write("\t<div class=\"col-md-1\">\n");
      out.write("\t\t<div id=\"share-wrapper\">\n");
      out.write("\t\t\t<ul class=\"share-inner-wrp\">\n");
      out.write("\t\t\t\t<!-- Facebook -->\n");
      out.write("\t\t\t\t<li class=\"facebook button-wrap\"><a href=\"#\">Share</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Twitter -->\n");
      out.write("\t\t\t\t<li class=\"twitter button-wrap\"><a href=\"#\">Tweet it</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- LinkedIn -->\n");
      out.write("\t\t\t\t<li class=\"linked button-wrap\"><a href=\"#\">Linked In</a></li>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Google -->\n");
      out.write("\t\t\t\t<li class=\"google button-wrap\"><a href=\"#\"><b>g<sup>+</sup></b> Share</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");

		String error = null;
		try {
			error = (String) session.getAttribute("error");
		} catch (Exception e) {
			error = null;
		} finally {
			session.removeAttribute("error");
		}
	
      out.write("\n");
      out.write("\t<div class=\"wrapper\">\n");
      out.write("\t\t<div class=\"col-lg-12\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t");
      //  form:form
      org.springframework.web.servlet.tags.form.FormTag _jspx_th_form_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fform_005fform_0026_005fng_002dsubmit_005fname_005fmethod_005fdata_002dtoggle_005fclass_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
      _jspx_th_form_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_form_005fform_005f0.setParent(null);
      // /jsp/exam/examlogin.jsp(246,4) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setName("loginForm");
      // /jsp/exam/examlogin.jsp(246,4) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "class", "form-horizontal");
      // /jsp/exam/examlogin.jsp(246,4) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "ng-submit", "submitForm(loginForm.$valid)");
      // /jsp/exam/examlogin.jsp(246,4) null
      _jspx_th_form_005fform_005f0.setDynamicAttribute(null, "data-toggle", "validator");
      // /jsp/exam/examlogin.jsp(246,4) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setAction("examhome.htm");
      // /jsp/exam/examlogin.jsp(246,4) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_form_005fform_005f0.setMethod("post");
      int[] _jspx_push_body_count_form_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_form_005fform_005f0 = _jspx_th_form_005fform_005f0.doStartTag();
        if (_jspx_eval_form_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("\t\t\t\t\t<div class=\"panel-body\">\n");
            out.write("\t\t\t\t\t\t<div class=\"row\">\n");
            out.write("\t\t\t\t\t\t\t<div class=\"col-lg-8 panel-info\" style=\"float: left;\">\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading \">\n");
            out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-list-alt\"></i> Click on posts for further details\n");
            out.write("\t\t\t\t\t\t\t\t\t</h3>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-group\" id=\"accordion\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            if (_jspx_meth_c_005fforEach_005f0(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t/.col-lg-12 -->\n");
            out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4 panel-info\" style=\"float: right;\">\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user fa-1x\"></i> Online Examination - Login\n");
            out.write("\t\t\t\t\t\t\t\t\t</h3>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-body \">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<span style=\"padding-left: 40%; color: #3a87ad;\"> <i class=\"fa fa-user fa-4x\"></i>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</span>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" ng-class=\"{ 'has-error' : loginForm.email.$invalid && loginForm.email.$dirty }\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"emailId\" class=\"col-sm-2 control-label\">");
            if (_jspx_meth_spring_005fmessage_005f1(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</label>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\" style=\"color: rgb(50, 118, 177)\"><i class=\"fa fa-envelope-o fa-fw\"></i></span> <input type=\"email\" class=\"form-control\" name=\"email\" id=\"emailId\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Your Email...\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Please enter the Email ID your registered with us.\" ng-model=\"email\" maxlength=\"60\" required />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\"></p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block with-errors col-sm-offset-2 col-sm-8\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\t\t<span class=\"has-error help-block\" ng-show=\"loginForm.email.$error.required && !loginForm.email.$pristine\">Required!</span> -->\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\t\t<span class=\"has-error help-block\" ng-show=\"loginForm.email.$invalid && !loginForm.email.$pristine\">Not valid Email!</span>\t -->\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<p ng-show=\"loginForm.email.$invalid && loginForm.email.$dirty\" class=\"help-block\">Enter a valid email.</p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													if (error != null && error.equalsIgnoreCase("errorEmail")) {
												
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"notRegistered\" class=\"alert alert-danger alert-dismissable col-sm-12\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tEntered Email is <i>not registered</i> with us.\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\" ng-class=\"{ 'has-error' : loginForm.password.$invalid && !loginForm.password.$pristine }\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<label for=\"password\" class=\"col-sm-2 control-label\">");
            if (_jspx_meth_spring_005fmessage_005f2(_jspx_th_form_005fform_005f0, _jspx_page_context, _jspx_push_body_count_form_005fform_005f0))
              return;
            out.write("</label>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-group col-sm-8\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"input-group-addon\" style=\"color: rgb(50, 118, 177)\"><i class=\"fa fa-key fa-fw\"></i></span> <input type=\"password\" class=\"form-control\" id=\"password\" name=\"password\" required\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"Enter Your Password...\" required data-toggle=\"tooltip\" data-placement=\"left\" title=\"Enter Your password.\" ng-model=\"password\" required>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<p class=\"help-block\"></p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\" col-sm-offset-4 col-sm-8\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"has-error help-block\" ng-show=\"loginForm.password.$error.required && !loginForm.password.$pristine\">Required!</span>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block with-errors col-sm-offset-2 col-sm-8\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													if (error != null && error.equalsIgnoreCase("errorPassword")) {
												
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"notRegistered\" class=\"alert alert-danger alert-dismissable col-sm-12\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tEntered password does not match with the given email.\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-8\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary btn-block\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-sign-in\"></i> Sign in\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"clearfix\"></div>\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													if (error != null && error.equalsIgnoreCase("error")) {
												
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"notRegistered\" class=\"alert alert-danger alert-dismissable col-sm-12\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-hidden=\"true\">&times;</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tError during login! <br />Check credentials or use forgot password.\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

													}
												
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"notRegistered\" class=\"help-block with-errors col-sm-12\"> -->\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>Error during login! <br/>Check credentials or use forgot password.</p> -->\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t\t\t\t\t\t\t\t\t</div> -->\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-8\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<a onclick=\"forgotPassword()\" data-toggle=\"modal\" data-target=\"#forgotPassword\" href=\"#\">Forgot Password?</a> &nbsp;&nbsp;<span>|</span> &nbsp; <a href=\"registration.htm\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"pull-right\" onclick=\"redirect('registration.htm')\">Sign Up!</a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-8\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t<!-- \t\t\t\t\t\t/.row -->\n");
            out.write("\t\t\t\t\t\t\t<div class=\"col-lg-4 panel-info\" style=\"float: right;\">\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<h3 class=\"panel-title\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-globe fa-spin\"></i> News and Announcements\n");
            out.write("\t\t\t\t\t\t\t\t\t</h3>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-body\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"vticker\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<ul class=\"list-unstyled\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"alert alert-info\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tNew Recruitment Portal for MHRD-Project job openings at IIT Bombay is up. <a href=\"#\" class=\"alert-link\"></a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"alert alert-info\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tRecruitment for Spoken Tutorial Advertisement started on January 2014. <a href=\"#\" class=\"alert-link\">Spoken Tutorial Advertisement Started</a>.\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"alert alert-info\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tRecruitment for Spoken Tutorial Advertisement ended on January 2014. <a href=\"#\" class=\"alert-link\">Spoken Tutorial Advertisement Ended</a>.\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"alert alert-info\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tRegistered candidates can login in the new Recruitment interface and check their profile and Applied positions <a href=\"#\" class=\"alert-link\">Click for details</a>.\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</ul>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t<div id=\"social\"></div>\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_form_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_form_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_form_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_form_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_form_005fform_005f0.doFinally();
        _005fjspx_005ftagPool_005fform_005fform_0026_005fng_002dsubmit_005fname_005fmethod_005fdata_002dtoggle_005fclass_005faction.reuse(_jspx_th_form_005fform_005f0);
      }
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../includes/footer.jsp", out, false);
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(document).ready(function() {\n");
      out.write("\n");
      out.write("\t\tvar dd = $('.vticker').easyTicker({\n");
      out.write("\t\t\tdirection : 'up',\n");
      out.write("\t\t\teasing : 'swing',\n");
      out.write("\t\t\tspeed : 'slow',\n");
      out.write("\t\t\tinterval : 2000,\n");
      out.write("\t\t\theight : 'auto',\n");
      out.write("\t\t\tvisible : 3,\n");
      out.write("\t\t\tmousePause : 1,\n");
      out.write("\t\t\tcontrols : {\n");
      out.write("\t\t\t\tup : '.up',\n");
      out.write("\t\t\t\tdown : '.down',\n");
      out.write("\t\t\t\ttoggle : '',\n");
      out.write("\t\t\t\tstopText : 'Stop !!!'\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}).data('easyTicker');\n");
      out.write("\t});\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent(null);
    // /jsp/exam/examlogin.jsp(19,7) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f0.setCode("login.title");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/exam/examlogin.jsp(259,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("post");
    // /jsp/exam/examlogin.jsp(259,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/jsp/exam/examlogin.jsp(259,12) '${posts}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${posts}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel panel-default\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-heading\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<h4 class=\"panel-title\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a data-toggle=\"collapse\" data-parent=\"#accordion\" href=\"#collapse");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" onclick=\"changeAccordionImage('");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("')\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write(" <i\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"accordionImage");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"fa fa-expand pull-right\"></i></a>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</h4>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div id=\"collapse");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("\" class=\"panel-collapse collapse\">\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-body\" style=\"background-color: #fffefa\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.designationDescription}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
          out.write("</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"panel-footer\"></div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/exam/examlogin.jsp(291,63) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f1.setCode("login.label.email");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_form_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_form_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_form_005fform_005f0);
    // /jsp/exam/examlogin.jsp(318,64) name = code type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_spring_005fmessage_005f2.setCode("login.label.password");
    int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
      if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
    }
    return false;
  }
}
